### PR TITLE
Initial commit of design files

### PR DESCRIPTION
**Pull request by scottdarch**
There is one big step file in here but I don't know how to use git-lfs with a public fork?

### CODE REVIEW

**Comment by aentinger** [comment]
>There is one big step file in here but I don't know how to use git-lfs with a public fork?

I don't know either 😬 . But you could just create a branch on this repository, you should have sufficient rights for this ;)

**Comment by scottdarch** [comment]
Hmm. I do not have push rights for this repo.

**Comment by aentinger** [comment]
Push access granted, mea culpa, I forgot to add the team ... :(

**Comment by scottdarch** [comment]
Hmm, still can't push

**Comment by aentinger** [comment]
Just checked, you're the member of the enrich2023 team which has push access to this repo. Did you use a different user while pushing? I tried to add your handle individually but got the error that @scottdarch is already a collaborator 🤔

**Pull request closed without merging**
